name: vrptocho
channels:
  - defaults
dependencies:
  - certifi=2022.12.7=py37haa95532_0
  - pip=22.3.1=py37haa95532_0
  - python=3.7.0=hea74fb7_0
  - setuptools=65.6.3=py37haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.0
      - charset-normalizer==3.0.1
      - cloudpickle==2.2.1
      - cycler==0.11.0
      - fonttools==4.38.0
      - google-auth==2.16.1
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - gym==0.21.0
      - idna==3.4
      - importlib-metadata==4.13.0
      - kiwisolver==1.4.4
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.5.3
      - networkx==2.6.3
      - numpy==1.21.6
      - oauthlib==3.2.2
      - packaging==23.0
      - pandas==1.1.5
      - pillow==9.4.0
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - six==1.16.0
      - stable-baselines3==1.7.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torch==1.13.1
      - typing-extensions==4.5.0
      - urllib3==1.26.14
      - werkzeug==2.2.3
      - zipp==3.14.0